natural = @{ '1'..'9' ~ ASCII_DIGIT* }
int = @{ ("+" | "-")? ~ ASCII_DIGIT+ }
num = @{ int ~ ("." ~ ASCII_DIGIT*)? ~ (^"e" ~ int)? }
dice = @{ natural ~ "d" ~ natural? }

operation = _{ add | subtract | multiply | divide }
add       = { "+" }
subtract  = { "-" }
multiply  = { "*" }
divide    = { "/" }

expr = { term ~ (operation ~ term)* }
term = _{ dice | num | "(" ~ expr ~ ")" }

calculation = _{ SOI ~ expr ~ EOI }

WHITESPACE = _{ " " | "\t" }