ws = _{ WHITE_SPACE | "\r" | "\n" | "\t" }

dq_string = ${ "\"" ~ dq_inner ~ "\"" }
dq_inner = @{ dq_char* }
dq_char = {
    !("\"" | "\\") ~ ANY | "\\" ~ ("\"" | "\\" | "/")
}

sq_string = ${ "'" ~ sq_inner ~ "'" }
sq_inner = @{ sq_char* }
sq_char = {
    !("'" | "\\") ~ ANY | "\\" ~ ("'" | "\\" | "/")
}

string = ${ inner }
inner = @{ char+ }
char = { !ws ~ ANY }

arg = _{ (dq_string | sq_string | string) }
args = _{ SOI ~ ws* ~ arg ~ (ws+ ~ arg)* ~ ws* ~ EOI }